Add package abstraction
rhos-infra/znoyder pull request #24
Opened 2022-02-17 10:51 UTC by bregman-arie

This will allow us to easily access package attributes
in addition to running some operations seemingly like
printing out information on the package.

2022-02-17 12:41 UTC, sdatko requested changes
This breaks now the generator... IMO introducing the Package data class package should not require that many changes in browser.

Lets jump on google meet to address this.

2022-02-17 12:51 UTC, bregman-arie commented
Yes, as I told you, it's initial work, don't expect it to work at the moment :)
Just looking for initial feedback before proceeding to generator

2022-02-17 12:58 UTC, sdatko commented on znoyder/package.py
> +                                 self.osp_patches)
Just osp_name or osp_project here

2022-02-17 18:29 UTC, bregman-arie commented on znoyder/package.py
> +                                 self.osp_patches)
Done

2022-02-21 11:22 UTC, IgnacioPro approved these changes
Looks good to me.

2022-02-23 21:02 UTC, bregman-arie commented
Closing this one since there was not enough support for merging it and there was a decision to focus on other aspects of the project like writing unit tests for the existing codebase.

2022-02-23 21:02 UTC, closed without merging